# Generated by Django 3.0.8 on 2020-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200802_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
